### ISSUE TITLE
DMCA from Pascal Glitcher

### ISSUE THREAD

**Issue by NekoAlosama** [Chaython/Raytracing-path-tracing-RTGI-Reshade#3]
https://www.lumendatabase.org/notices/20380490

According to the copyright claim, a sharable Google Drive folder from Pascal Glitcher dating back to Nov. 12, 2019, is the original source of version 0.8.0.2. That version contains a licence agreement that says that says that (re-)distribution of this version is not allowed. Where is your source that it was under Creative Commons? Pascal Glitcher doesn't seem to agree that this is okay.

**Comment by NekoAlosama** [comment]
@Chaython

**Comment by Chaython** [comment]
This is from his patreon. It used the creative commons license in the file.
I spoke to him, he didn't like it and has since removed creative commons license on future releases.

**Comment by NekoAlosama** [comment]
Understood. At least the current version is at >0.9.0.0 or whatever.

**Comment by Chaython** [comment]
I believe the newest is 0.11
